# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

www.bestchange.com	FALSE	/	FALSE	0	PHPSESSID	glsgnrvdgs8ibv4d842f18m255
www.bestchange.com	FALSE	/	FALSE	1858934424	userid	2abd884db982fbcb252df223dcb76265
www.bestchange.com	FALSE	/	FALSE	1858934424	source	m%D9XL%8D%3F%1A%EB%05z%16%83%80%CB%BC%F1%7DO%B3%B8%7C%F3%22%9E%033%2B%E4%F5c%B5%D2%AC%A6n%A5%5D%BE%A9%1ADm%D1%0FK4e%29D%9D%3E%AF
www.bestchange.com	FALSE	/	FALSE	1858934424	partner_id	691208
